### ISSUE TITLE
Download Chapter after X-chapter only

### ISSUE THREAD

**Issue by Shikitsuna** [v613/toonily-dl#1]
skip checking files and download from x-chapter instead
i using image compressor which converting the images to webp to make it smaller and when i update the chapter it will overwrite instead, i suggest to only download after x-chapter eg, 140 so it will dl after ch 140 only

**Comment by v613** [comment]
Thanks @Shikitsuna for a good idea.
I had in plan to download exactly indicated chapter (picked one, as is named in README.md)

Now I see it will be more useful to use range/interval mechanism.

**Comment by Shikitsuna** [comment]
thanks, i read the readme before and i thought it would be a hassle if it only add to indicated chapters, with range it would be more benefit, so you can choose either single or range of chapters
example like, -ch 499 (single) -ch 423-500 (range) -ch 500+ (than ch 500)

**Comment by v613** [comment]
Implemented in release `v.1.1`
Examples of usage can be found in README.md
