### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Shikitsuna** [v613/toonily-dl#4]
**Auto Split Images More than 5000px**
Sometimes, i encounter images over 20K long tall page, if possible split the images to 5000px each and rename it into imagesname_A imagesname_B or similar
**Auto Renumber chapter filenames and chapters**
use 001 020 (3 digit system instead) so 001.png 002.png, with the split images, the name will be 001_A.png 001_B.png etc,
same as chapter, i use advanced renamer but, quite troublesome, so chapter-001 chapter-002 because android and things like natural number sort order will sort 1 then 10 and 100 if no first 0-digit to next

**Comment by v613** [comment]
**Split Images**:
It's a bit out of scope, but it's interesting to have such feature. I need to analyze a bit few images.

**Auto Renumber**: In the case of images, they are implicitly formatted with two digits (for example, 01, 05, 23, etc.). Generally, this format should prevent sorting issues. Did you saw comics/manga that had more than 99 images in chapter ?.

**Comment by Shikitsuna** [comment]
Sorry for late answer, An Outsider Way's in on Toonily are ranged from 80 to 160 images per chapters so i think 3 digit number format will do.
for the image you can look "That’s Not How You Do It" chapter-45, there's 14K pixel image tall and 23K image tall there, or "Circles", Ch 13, all of them are like 20K pixel tall, this will problematic when converted to webp wich only can support 16.3K pixel width/height

**Comment by v613** [comment]
@Shikitsuna from what I noticed in the manga indicated by you "An Outsider Way" the images have 3 digit number format. However, I have added the change to the part with chapters - thank you.

I must mention that the chapters with names other than "chapter-N" are downloaded regardless of the indicated range (like "epilogue")

During tests with such large chapters, a high processing time was observed (right side of the image). In this sense, a concurrent mode of downloading the images from the chapter has been adopted (left side of the image).
![decrease download time](https://github.com/v613/toonily-dl/assets/15879258/843ffb13-c36b-4f26-90d1-5d2f74f3635b)

#### Splitting Images
What about splitting images, I decided to include them in next release in the golang version only. Adding functionality to the shell version involves external dependencies such as ImageMagic, which goes against the project's goal of using no dependencies.


[Release v0.2.0](https://github.com/v613/toonily-dl/releases/tag/v0.2.0)

**Comment by Shikitsuna** [comment]
Thanks, I guess the split image parts can't be done much without dependencies, but overall this is very good improvement. tested and it's working nicely (for now).
